[versions]
sykepengerGradlePlugins = "20261001.1830"
tbd-libs = "20261005.1432"

[libraries]
cloud-sql-postgres-socket-factory = "com.google.cloud.sql:postgres-socket-factory:1.30.0"
flyway-database-postgresql = "org.flywaydb:flyway-database-postgresql:13.8.1"
hikaricp = "com.zaxxer:HikariCP:7.1.0"
kotliquery = "com.github.seratch:kotliquery:1.9.1"
postgresql = "org.postgresql:postgresql:42.7.13"
rapids-and-rivers = "com.github.navikt:rapids-and-rivers:2026091610031789545782"
sykepengerLibs-logging = "no.nav.sykepenger.libs:logging:20261001.1823"
tbd-libs-postgres-testdatabaser = { module = "com.github.navikt.tbd-libs:postgres-testdatabaser", version.ref = "tbd-libs" }
tbd-libs-rapids-and-rivers-test = { module = "com.github.navikt.tbd-libs:rapids-and-rivers-test", version.ref = "tbd-libs" }

[plugins]
sykepenger-deployable = { id = "no.nav.sykepenger.deployable", version.ref = "sykepengerGradlePlugins" }
sykepenger-root = { id = "no.nav.sykepenger.root", version.ref = "sykepengerGradlePlugins" }
