apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spock
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /metrics
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        pointInTimeRecovery: true
        tier: db-f1-micro
        name: spock
        databases:
          - name: spock
            envVarPrefix: DATABASE
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spock-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
