apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spock-opprydding-dev
  namespace: tbd
  labels:
    team: tbd
    dbPolicyUser: spock_opprydding_dev
spec:
  port: 8080
  startup:
    path: isready
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 9
  liveness:
    path: isalive
  readiness:
    path: isready
  preStopHook:
    http:
      path: /stop
  resources:
    requests:
      cpu: 50m
      memory: 320Mi
    limits:
      memory: 512Mi
  replicas:
    min: 1
    max: 1
  strategy:
    type: Recreate
  kafka:
    pool: nav-dev
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  prometheus:
    enabled: true
    path: /metrics
  envFrom:
    - secret: google-sql-spock-spock-spock-opprydding-dev-ef054e0b
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spock-opprydding-dev-v1
    - name: KAFKA_RESET_POLICY
      value: latest
    - name: DATABASE_REGION
      value: europe-north1
    - name: DATABASE_INSTANCE
      value: spock
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
