apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spock
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  prometheus:
    enabled: true
    path: /metrics
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        pointInTimeRecovery: true
        tier: db-custom-4-15360
        name: spock
        databases:
          - name: spock
            envVarPrefix: DATABASE
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  env:
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-spock-v1
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: KAFKA_RESET_POLICY
    value: none


