DELETE FROM paminnelse WHERE tilstand IN (
  'AVVENTER_SØKNAD_UFERDIG_FORLENGELSE',
  'AVVENTER_SØKNAD_FERDIG_FORLENGELSE',
  'AVVENTER_SØKNAD_FERDIG_GAP',
  'AVVENTER_SØKNAD_UFERDIG_GAP',
  'MOTTATT_SYKMELDING_FERDIG_FORLENGELSE',
  'MOTTATT_SYKMELDING_UFERDIG_FORLENGELSE',
  'MOTTATT_SYKMELDING_FERDIG_GAP',
  'MOTTATT_SYKMELDING_UFERDIG_GAP'
);