UPDATE paminnelse
SET tilstand='AVVENTER_INNTEKTSMELDING_ELLER_HISTORIKK'
WHERE tilstand IN (
    'AVVENTER_INNTEKTSMELDING_ELLER_HISTORIKK_FERDIG_GAP',
    'AVVENTER_INNTEKTSMELDING_UFERDIG_GAP',
    'AVVENTER_INNTEKTSMELDING_FERDIG_FORLENGELSE',
    'AVVENTER_INNTEKTSMELDING_UFERDIG_FORLENGELSE'
);
