UPDATE paminnelse SET neste_paminnelsetidspunkt='2020-05-07 11:45:00.000000' WHERE tilstand IN (
    'AVVENTER_GODKJENNING',
    'MOTTATT_SYKMELDING_FERDIG_FORLENGELSE',
    'MOTTATT_SYKMELDING_UFERDIG_FORLENGELSE',
    'MOTTATT_SYKMELDING_FERDIG_GAP',
    'MOTTATT_SYKMELDING_UFERDIG_GAP',
    'AVVENTER_SØKNAD_FERDIG_GAP',
    'AVVENTER_INNTEKTSMELDING_UFERDIG_GAP',
    'AVVENTER_UFERDIG_GAP',
    'AVVENTER_INNTEKTSMELDING_UFERDIG_FORLENGELSE',
    'AVVENTER_UFERDIG_FORLENGELSE',
    'AVVENTER_SØKNAD_UFERDIG_FORLENGELSE',
    'AVVENTER_SØKNAD_UFERDIG_GAP',
    'AVVENTER_INNTEKTSMELDING_FERDIG_GAP'
);
